# Generated by Django 2.2.7 on 2019-12-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191211_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, height_field=918, upload_to='static/media', width_field=446),
        ),
    ]
