# Generated by Django 2.2.7 on 2019-12-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191215_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='<django.db.models.fields.SlugField>/'),
        ),
    ]
