# Generated by Django 2.2.7 on 2019-12-16 20:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20191216_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('date_pub', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
