# Generated by Django 2.2.7 on 2020-04-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200427_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.PostLikes'),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='sessionId',
            field=models.CharField(default=True, max_length=128),
        ),
    ]
