# Generated by Django 2.2.7 on 2020-05-03 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200427_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PostCountViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesId', models.CharField(db_index=True, max_length=150)),
                ('postId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
